exclude: '^tests/output_filters/data/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.16.0
    hooks:
    -   id: reorder-python-imports
        exclude: setup.py
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|\.pre-commit-config\.yaml
-   repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
    -   id: black
