[mypy]
python_version = 3.12
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_subclassing_any = False
disallow_any_generics = False
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
show_error_context = True
show_column_numbers = True
ignore_missing_imports = True
