name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        architecture: x64

    - name: Install dependencies
      run: python3 -m pip install tox

    - name: Run all tests
      run: tox
